// ==========================================================================
// KATEGORIEN-DATEN — Anime Plot Maker
// ==========================================================================

const CATEGORIES = [
  {
    key: "role",
    label: "Rolle",
    icon: "🎭",
    entries: [
      "Protagonist","Deuteragonist","Tritagonist","Antagonist","Side-Charakter",
      "NPC","Kleiner Fiesling","Anti-Held","Rivale","Mastermind im Hintergrund",
      "Comic Relief","Verräter","Wächter","Söldner","Einzelgänger",
      "Anführer der Gruppe","Stellvertreter des Anführers","Neuling","Veteran",
      "Geheimwaffe","Schatten-Charakter","Katalysator der Handlung","Love Interest",
      "Tragischer Held","Gefallener Held","Chronist der Geschichte","Herausforderer",
      "Wildcard","Doppelagent","Bodyguard","Strategin im Hintergrund",
      "Letzte Verteidigungslinie","Symbolfigur des Widerstands","Werkzeug des Bösewichts",
      "Rächer","Gejagter","Jäger","Vermittler zwischen den Fraktionen"
    ]
  },
  {
    key: "world",
    label: "Anime-Welt",
    icon: "🌍",
    entries: [
      "Attack on Titan","Seven Deadly Sins","Demon Slayer","Naruto","One Piece","Bleach",
      "My Hero Academia","Jujutsu Kaisen","Dragon Ball","Fullmetal Alchemist",
      "Hunter x Hunter","Death Note","Fairy Tail","Black Clover","Tokyo Ghoul",
      "One Punch Man","Chainsaw Man","Mob Psycho 100","Sword Art Online","Re:Zero",
      "Overlord","Tensei Shitara Slime Datta Ken","The Rising of the Shield Hero",
      "Vinland Saga","Berserk","JoJo's Bizarre Adventure","Cowboy Bebop",
      "Neon Genesis Evangelion","Code Geass","Spy x Family","Haikyuu","Dr. Stone",
      "Made in Abyss","Violet Evergarden","Steins;Gate","The Promised Neverland",
      "Kaguya-sama: Love is War","Soul Eater","Fire Force","Assassination Classroom"
    ]
  },
  {
    key: "archetype",
    label: "Archetyp",
    icon: "🧬",
    entries: [
      "Feigling (rennt vor Kämpfen lieber weg, als sich zu stellen)",
      "Genie (denkt im Kampf immer zehn Züge voraus)",
      "Heißblütiger Kämpfer (handelt aus dem Bauch heraus statt zu planen)",
      "Eiskalter Stratege (zeigt nie Emotionen, kalkuliert jeden Zug)",
      "Beschützer (stellt sich ohne zu zögern für andere in Gefahr)",
      "Trickster (gewinnt lieber durch List als durch rohe Kraft)",
      "Loyaler Diener (folgt seinem Anführer bedingungslos)",
      "Einzelgänger (vertraut grundsätzlich niemandem)",
      "Idealist (glaubt fest an das Gute in jedem Menschen)",
      "Zyniker (glaubt an gar nichts mehr, erwartet immer das Schlimmste)",
      "Rachsüchtiger (lebt nur noch für die eigene Vergeltung)",
      "Optimist (verliert selbst in aussichtslosen Lagen nie die Hoffnung)",
      "Perfektionist (akzeptiert weder bei sich noch bei anderen Fehler)",
      "Chaot (handelt komplett unvorhersehbar, selbst für Verbündete)",
      "Workaholic-Kämpfer (trainiert ohne Rücksicht auf den eigenen Körper)",
      "Beschützer-Anführer (stellt das Team immer über sich selbst)",
      "Stiller Beobachter (spricht wenig, bemerkt aber alles zuerst)",
      "Angeber (übertreibt die eigene Stärke gerne vor Publikum)",
      "Spätzünder (wirkt am Anfang schwach, wird am Ende unaufhaltsam)",
      "Wolf im Schafspelz (wirkt harmlos, ist im Kern brandgefährlich)",
      "Gebrochener Held (kämpft trotz eigener, nie verheilter Wunden weiter)",
      "Fanatiker (stellt die eigene Ideologie über alles andere)",
      "Melancholiker (hängt ständig der eigenen Vergangenheit nach)",
      "Kindlicher Naivling (versteht die Konsequenzen des eigenen Handelns nicht)",
      "Kontrollfreak (will jede Situation bis ins Detail durchplanen)",
      "Draufgänger (stürzt sich ohne Plan kopfüber ins Risiko)",
      "Mutterfigur (kümmert sich aufopfernd um die ganze Gruppe)",
      "Rebell (lehnt sich grundsätzlich gegen jede Autorität auf)",
      "Pflichtbewusster Soldat (ein Befehl steht für ihn über allem)",
      "Genügsamer Weiser (sucht im Gegensatz zu allen anderen keine Anerkennung)",
      "Schmeichler (manipuliert seine Gegner lieber mit Worten als mit Fäusten)",
      "Berserker (verliert im Kampf regelmäßig die Kontrolle über sich selbst)",
      "Analytiker (kämpft ausschließlich nach Wahrscheinlichkeiten und Daten)",
      "Idol (kämpft vor allem für Ruhm und ein großes Publikum)",
      "Geist der Vergangenheit (lebt fast nur noch in alten Erinnerungen)",
      "Waise mit Mission (sucht nach einem großen Verlust einen neuen Sinn)",
      "Unterschätzter Underdog (wird von allen ständig belächelt)"
    ]
  },
  {
    key: "backstory",
    label: "Backstory",
    icon: "📖",
    entries: [
      "das Heimatdorf wurde von einem Monster ausgelöscht",
      "die eigene Familie wurde durch einen Verrat ausgelöscht",
      "als Kind von einem legendären Meister aufgenommen worden",
      "ein geheimes Experiment am eigenen Körper überlebt",
      "aus einer völlig anderen Welt hierher transportiert worden",
      "als einzige Person ein Massaker überlebt",
      "aus königlichem Blut, das jahrelang verborgen wurde",
      "von der eigenen Organisation verstoßen worden",
      "in einem jahrelangen Krieg aufgewachsen",
      "als Waffe für eine geheime Organisation gezüchtet worden",
      "hat jede Erinnerung an die eigene Vergangenheit verloren",
      "hat als Kind ein mächtiges Wesen gerettet und wurde dafür markiert",
      "stand früher selbst auf der Seite des Bösen",
      "hat jahrelang im Verborgenen nur für Rache trainiert",
      "unter einer falschen Identität aufgewachsen",
      "die Vernichtung der eigenen Heimatwelt überlebt",
      "vom eigenen Dorf wegen einer besonderen Kraft verstoßen worden",
      "als Straßenkind ganz allein groß geworden",
      "war jahrelang Gefangener eines mächtigen Feindes",
      "hat einen alten Familienfluch der Vorfahren geerbt",
      "wurde vom eigenen Geschwisterteil verraten",
      "hat den besten Freund direkt vor den eigenen Augen im Kampf verloren",
      "in völliger Isolation fernab jeder Zivilisation aufgewachsen",
      "war jahrelang Teil eines streng geheimen Ordens",
      "hat ein tödliches Turnier als Einzige oder Einziger überlebt",
      "wurde als Kind ausgesetzt und von Fremden großgezogen",
      "musste schon als Kind die Verantwortung für jüngere Geschwister tragen",
      "diente früher selbst als Soldat auf der Seite des heutigen Feindes",
      "hat einst einen Pakt mit einem übernatürlichen Wesen geschlossen",
      "ist mit wilden Tieren statt mit Menschen aufgewachsen",
      "hat die eigene Heimat durch eine Naturkatastrophe verloren",
      "war Opfer grausamer medizinischer Experimente",
      "ist aus einem totalitären Regime geflohen",
      "wurde erst im Erwachsenenalter zum ersten Mal von der eigenen Kraft überrascht",
      "ist als Doppelgänger einer wichtigen historischen Figur aufgewachsen",
      "hat ein Attentat auf die eigene Familie nur knapp überlebt"
    ]
  },
  {
    key: "ability",
    label: "Fähigkeit",
    icon: "✨",
    entries: [
      "Six Eyes (perfekte Wahrnehmung jeder Energie im Raum)",
      "Sharingan (kopiert und durchschaut jede gegnerische Technik)",
      "Byakugan (sieht durch Wände und die Chakrapunkte des Gegners)",
      "Rinnegan (beherrscht alle sechs Elemente und den Pfad zwischen Leben und Tod)",
      "Teufelsfrucht-Kraft (verleiht eine einzigartige, unnatürliche Fähigkeit)",
      "Titan-Verwandlung (kann sich in einen gigantischen Titanen verwandeln)",
      "Bankai (die endgültige, mächtigste Form der eigenen Klingenseele)",
      "Nen-Fähigkeit (formt die eigene Lebensenergie zu Waffen oder Schutzschilden)",
      "Alchemie (zerlegt und formt Materie nach dem Gesetz des Äquivalententauschs)",
      "Haki (spürt Absichten voraus und bricht die Willenskraft des Gegners)",
      "Chidori-artige Blitztechnik (bündelt Energie zu einem durchschlagenden Stoß)",
      "Domain Expansion (erschafft einen Raum, in dem die eigenen Angriffe garantiert treffen)",
      "Fluchtechnik (verwandelt negative Emotionen in zerstörerische Energie)",
      "Quirk-artige Sonderkraft (eine einzigartige, körpereigene Superkraft)",
      "Eismagie (friert Gegner und Umgebung in Sekunden ein)",
      "Requip-Magie (wechselt blitzschnell Rüstung und Waffen mitten im Kampf)",
      "Zeitmanipulation (verlangsamt, beschleunigt oder spult die Zeit zurück)",
      "Raummanipulation (faltet oder verschiebt den Raum um sich herum)",
      "Feuerbändigung (beherrscht Flammen als Waffe und Schutzschild)",
      "Schattenmanipulation (formt aus dem eigenen Schatten Klingen und Ketten)",
      "Übermenschliche Geschwindigkeit (bewegt sich schneller als das Auge folgen kann)",
      "Heilfähigkeit (schließt Wunden bei sich und anderen fast augenblicklich)",
      "Telepathie (liest Gedanken und sendet eigene direkt ins Bewusstsein anderer)",
      "Illusionsmagie (lässt Gegner völlig falsche Realitäten erleben)",
      "Seelenbindung (verbindet die eigene Seele mit Verbündeten oder Waffen)",
      "Elementkontrolle (beherrscht Wasser, Erde, Luft und Feuer gleichermaßen)",
      "Unsterblichkeitsfluch (regeneriert sich aus jeder noch so tödlichen Wunde)",
      "Formwandlung (verändert die eigene Körperform nach Belieben)",
      "Energie-Absorption (saugt gegnerische Angriffe auf und macht sie zu eigener Kraft)",
      "Schattenklon-Technik (erschafft beliebig viele exakte Kopien von sich selbst)",
      "Größenveränderung (wächst oder schrumpft je nach Kampfsituation)",
      "Blutkontrolle (manipuliert das eigene Blut oder das des Gegners als Waffe)",
      "Gravitationsmanipulation (verändert das Gewicht von sich selbst und der Umgebung)",
      "Marionettentechnik (steuert Gegner oder Konstrukte wie Marionetten aus der Ferne)",
      "Beschwörungsmagie (ruft mächtige Kreaturen als Verbündete in den Kampf)",
      "Precognition (sieht Sekundenbruchteile vor allen anderen, was als Nächstes passiert)",
      "Klangwellen-Technik (nutzt Schall als unsichtbare, durchschlagende Waffe)"
    ]
  },
  {
    key: "weapon",
    label: "Waffe",
    icon: "⚔️",
    entries: [
      "drei Schwerter im Stil von Zoro","Tessaiga, das Reißzahn-Schwert eines Dämons",
      "ein persönlicher Zanpakuto mit eigenem Willen","Kusanagi, die legendäre Wolkenschwert-Klinge",
      "ein Todesnotizbuch, das jeden hineingeschriebenen Namen tötet",
      "einen Gunbai-Kriegsfächer","ein Kettenschwert mit ausfahrbarer Klinge",
      "Sense und Kette wie ein Shinigami","einen verwandelbaren Kampfstab",
      "zwei gebogene Doppelklingen","einen Kriegshammer, der Erdstöße auslöst",
      "eine Kombination aus Schild und Kurzschwert","ein Katana mit einem eigenen Fluch",
      "Kampfhandschuhe mit ausfahrbaren Klingen","einen langen Kriegsspeer",
      "Wurfsterne und versteckte Klingen","Tonfa-Stöcke für Nahkampf",
      "einen Zauberstab, der Elementarmagie kanalisiert",
      "ein riesiges Zweihandschwert, größer als der eigene Körper",
      "eine Kampfsense mit langer Reichweite",
      "eine Kombination aus Bogen und verborgener Klinge",
      "bloße Fäuste, trainiert wie tödliche Waffen","eine Mondsichel-artige Klinge",
      "einen dornenbesetzten Morgenstern","ein filigranes Rapier für Duelle",
      "einen Kampffächer mit verborgenen Klingen",
      "ein beschworenes Arsenal wechselnder Waffen",
      "eine Waffe, die sich mit dem eigenen Element auflädt",
      "ein Paar Wurfdolche","eine Bola zum Fesseln von Gegnern",
      "eine Kriegskama mit Kette","eine Handkanone mit magischer Munition",
      "eine Klinge, die aus dem eigenen Blut geschmiedet wurde",
      "einen Kampfstab mit ausfahrbaren Sensenklingen",
      "ein Paar Kurzschwerter für Windschritt-Kombos",
      "eine Rüstungsklinge, die mit dem Träger verschmilzt"
    ]
  },
  {
    key: "finalform",
    label: "Finale Form",
    icon: "🔥",
    entries: [
      "Super-Saiyajin-artige goldene Machtform","finales Bankai in einer zweiten Stufe",
      "vollständig gepanzerte Incursio-Rüstung","ein mechanisches Cyber-Skelett voller Energie",
      "Neunschwänziger-Chakra-Modus","Ultra-Instinct-artiger, automatischer Kampfmodus",
      "eine fünfte Gear-Stufe voller absurder Kraft","perfekte Susanoo-Rüstung aus reiner Energie",
      "eine vollständig ausgewachsene, monströse Form","ein tobender Berserker-Modus ohne Kontrolle",
      "eine strahlende Engelsform","eine finstere Dämonenform",
      "eine gewaltige Drachenform","eine Transformation unter Vollmondlicht",
      "eine uralte Kriegsrüstung, die sich selbst aktiviert",
      "die Gestalt eines göttlichen Avatars","eine Fusion mit dem eigenen inneren Schatten",
      "eine gigantische Titanenform","einen Übermodus mit strengem Zeitlimit",
      "eine doppelte Entfesselung der eigenen Kraft","ein Erwachen des uralten Familienblutes",
      "eine Fusion mit dem engsten Verbündeten","ein finales Bankai der zweiten Stufe",
      "einen Kristallpanzer aus reiner Willenskraft","eine Feuerphönix-Form aus purer Energie",
      "einen völligen Chaos-Modus ohne Grenzen","ein absolutes Territorium um den eigenen Körper",
      "eine Manifestation der eigenen Seele als Kampfform",
      "ein Erwachen der Krone der Vorfahren","das komplette Freisetzen des Urzustands",
      "eine Rüstung aus dem Erbe der Ahnen","einen Herz-Overdrive-Modus",
      "einen wahren Meister-Modus jenseits normaler Grenzen",
      "eine endgültige, bestialische Kampfform","eine Erzengel-artige Lichtform",
      "eine ultimative Fusion aller eigenen Kräfte"
    ]
  },
  {
    key: "crewmate",
    label: "Crewmate",
    icon: "🤝",
    entries: [
      "Levi","Gojo","Zoro","Sanji","Naruto","Sasuke","Ichigo","Rukia","Killua","Kirito",
      "Erza","Natsu","Tanjiro","Nezuko","Deku","Bakugo","Todoroki","Luffy","Nami","Chopper",
      "Vegeta","Goku","Edward Elric","Alphonse Elric","Saitama","Genos","Denji","Power",
      "Meliodas","Ban","Rimuru","Guts","Light Yagami","L","Kaneki","Mob","Reigen",
      "Hinata Shoyo","Kageyama Tobio","Asta"
    ]
  },
  {
    key: "pet",
    label: "Pet / Begleiter",
    icon: "🐾",
    entries: [
      "Happy, der fliegende blaue Kater","Pochita, der kleine Kettensägenteufel",
      "Kon, der Plüschtier-Geist","Plue, das seltsame kleine Schneewesen",
      "Kero, der plüschige Beschützer","Kyubey, das rätselhafte weiße Wesen",
      "ein Drachenbaby, das gerade erst geschlüpft ist","ein Phönix-Küken mit ungewöhnlicher Wärme",
      "ein Schattenwolf, der nur dem eigenen Willen folgt","ein Feenfamiliar mit eigenem Kopf",
      "ein sprechender Schwertgeist im eigenen Griff","ein Fuchsgeist-Begleiter mit neun Schwänzen",
      "ein winziger Golem aus altem Gestein","ein fliegender Kater mit Fledermausflügeln",
      "eine Eule, die als Familiar Nachrichten überbringt","ein Schleim-Haustier mit erstaunlichem Appetit",
      "ein Katzendämon mit zwei Schwänzen","keinen Begleiter, reist bewusst allein",
      "ein kleines Robotertier aus alten Zeiten","einen Geisterhund, der niemanden im Stich lässt",
      "einen Kristallgolem-Begleiter","ein Baby-Phönix mit heilenden Tränen",
      "einen sprechenden Raben mit scharfer Zunge","einen magischen Frosch mit Weissagungen",
      "einen kleinen Traumfresser, der Albträume frisst","einen Sternenwal in Miniaturgröße",
      "einen Papagei, der heimlich als Spion arbeitet","eine Feuerechse mit kurzem Temperament",
      "einen Wind-Elementargeist, der ständig herumwirbelt","ein winziges Insektenschwarm-Wesen",
      "einen treuen Wolf aus dem Heimatdorf"
    ]
  },
  {
    key: "mentor",
    label: "Mentor",
    icon: "🧙",
    entries: [
      "Kakashi Hatake","Might Guy","Kisuke Urahara","Jiraiya","Shanks","Silvers Rayleigh",
      "Whitebeard","Meister Roshi","Piccolo","Yoruichi Shihouin","All Might",
      "Genryusai Yamamoto","King, der Grand Master","Merlin","Gildarts Clive","Makarov Dreyar",
      "Ging Freecss","Isaac Netero","Silva Zoldyck","Zeff","Dracule Mihawk","Escanor",
      "Giyu Tomioka","Sakonji Urokodaki","Kyojuro Rengoku","Byakuya Kuchiki",
      "Shota Aizawa","Vegeta als knallharter Lehrmeister","Ryuk, ein zwielichtiger Mentor",
      "eine anonyme wandernde Weise","Master Roshi-artiger Eremit in den Bergen",
      "eine alte Schwertmeisterin im Ruhestand","ein ehemaliger Erzfeind, der zum Lehrer wurde",
      "ein Geist der eigenen Vorfahren","ein strenger Ausbilder einer Geheimorganisation"
    ]
  },
  {
    key: "nemesis",
    label: "Erzfeind",
    icon: "💀",
    entries: [
      "Sosuke Aizen","Frieza","Madara Uchiha","Meruem","Griffith","Dio Brando",
      "Muzan Kibutsuji","Tomura Shigaraki","Ryomen Sukuna","Orochimaru","Pain",
      "Donquixote Doflamingo","Kaido","Big Mom","Light Yagami","Near",
      "Marshall D. Teach alias Blackbeard","Akaza","Enel","Sir Crocodile",
      "Yuno Gasai","Envy","Father","Johan Liebert","Shou Tucker","Zeref Dragneel",
      "Acnologia","Illumi Zoldyck","Toga Himiko","Kai Chisaki alias Overhaul",
      "All For One","Rob Lucci","Caesar Clown","Kars","Diavolo","Yhwach",
      "Gyutaro","Genryu, ein gefallener Held aus alten Legenden"
    ]
  },
  {
    key: "flaw",
    label: "Fataler Nachteil",
    icon: "⚠️",
    entries: [
      "jeder Power-Up frisst spürbar Lebenszeit",
      "redet im Kampf grundsätzlich zu viel, statt zu handeln",
      "handelt in entscheidenden Momenten immer zu überstürzt",
      "kann nicht tatenlos zusehen, selbst wenn Eingreifen taktisch falsch ist",
      "verliert bei aufkommender Wut komplett die Kontrolle",
      "kämpft aus Angst zu töten nie mit voller Kraft",
      "unterschätzt aus purer Arroganz jeden Gegner",
      "vertraut neuen Verbündeten viel zu schnell",
      "kann nicht kämpfen, ohne dass jemand zusieht",
      "braucht ein spezielles Item, um die eigene Kraft überhaupt zu halten",
      "wird bei Vollmond spürbar schwächer",
      "kann die stärkste Form nur für begrenzte Zeit halten",
      "verliert bei jedem Krafteinsatz ein Stück der eigenen Erinnerung",
      "muss erst selbst Schaden erleiden, um wirklich stark zu werden",
      "kämpft aus Prinzip nur mit einer Hand",
      "kann die eigenen Emotionen im Kampf nicht kontrollieren",
      "wird beim Einsatz der stärksten Fähigkeit vorübergehend blind",
      "zahlt für jede Kraftsteigerung mit dem Verlust eines Körperteils",
      "weigert sich aus Prinzip, bestimmte Gegner überhaupt anzugreifen",
      "muss dem Gegner vor jedem Kampf erst die eigenen Regeln erklären",
      "kann grundsätzlich nicht lügen, selbst wenn es überlebenswichtig wäre",
      "hört im Kopf ständig Stimmen aus der eigenen Vergangenheit",
      "wird von einem inneren Fluch langsam aber sicher aufgezehrt",
      "kollabiert nach jedem Krafteinsatz für Tage",
      "kann alte Wut auf einen bestimmten Feind niemals ganz kontrollieren",
      "opfert mit jeder Kraftsteigerung ein Stück der eigenen Sinne",
      "altert bei jedem Einsatz der stärksten Fähigkeit sichtbar",
      "verliert das eigene Gedächtnis in unvorhersehbaren Fragmenten",
      "kann ohne ausreichend Nahrung die eigene Kraft nicht halten",
      "wird von der eigenen Vergangenheit im entscheidenden Moment gelähmt",
      "kämpft aus Ehrgefühl oft zu fair für den eigenen Vorteil",
      "kann echten Verrat aus Vertrauen einfach nicht erkennen"
    ]
  },
  {
    key: "twist",
    label: "Plot Twist",
    icon: "🌀",
    entries: [
      "ein Zeitloop, der sich erst mit dem richtigen Ausgang durchbricht",
      "ein enger Verbündeter entpuppt sich als Verräter",
      "der eigene Mentor war von Anfang an der wahre Bösewicht",
      "der Erzfeind stellt sich als verlorenes Familienmitglied heraus",
      "die eigenen Erinnerungen erweisen sich als gefälscht",
      "die gesamte Welt entpuppt sich als Simulation",
      "man selbst ist eigentlich der Antagonist einer anderen Zeitlinie",
      "der beste Freund stirbt und kehrt als erbitterter Feind zurück",
      "der eigene Begleiter ist in Wahrheit ein uraltes, mächtiges Wesen",
      "die eigene Fähigkeit entpuppt sich als jahrhundertealter Familienfluch",
      "das Königreich, das beschützt wurde, ist der wahre Feind",
      "man selbst ist ein Klon des echten Protagonisten",
      "diese Zeitlinie wurde bereits einmal komplett zerstört und neu erschaffen",
      "der Mentor opfert sich, um das entscheidende Wissen weiterzugeben",
      "der Erzfeind wollte die ganze Zeit über nur beschützen, nicht zerstören",
      "die eigene Organisation hat von Anfang an manipuliert",
      "das eigentliche Ziel der ganzen Reise existiert in Wahrheit gar nicht",
      "sämtliche Erinnerungen vor dem ersten Kapitel sind erfunden",
      "der beste Freund ist die Zukunftsversion von einem selbst",
      "das ganze Multiversum droht durch die eigene Entscheidung zu kollabieren",
      "ein enger Verbündeter ist als Spion einer fremden Macht eingeschleust",
      "eine geliebte Person aus der Vergangenheit hat nie wirklich existiert",
      "die reale Welt liegt in Wahrheit Jahrhunderte in der Zukunft",
      "eine alte Amnesie verbirgt eine dunkle Vergangenheit als Attentäter",
      "der Feind nutzt exakt dieselbe Fähigkeit aus einem sehr persönlichen Grund",
      "der Krieg wurde von einer neutralen dritten Partei absichtlich angezettelt",
      "das Heimatdorf aus der Kindheit hat es so nie gegeben",
      "die eigene Verwandlung ist in Wahrheit die Kontrolle eines Parasiten",
      "Meister und Schüler tauschen mitten in der Geschichte die Rollen",
      "die letzte Prüfung ist in Wahrheit ein Test durch die engsten Verbündeten"
    ]
  }
];

const CATEGORY_ORDER = CATEGORIES.map(c => c.key);
